### ISSUE TITLE
提交offset的那个地方是不是反了啊

### ISSUE THREAD

**Issue by JellyJellyJay** [jiankunking/jstorm-kafka-plugin-demo#2]
无论设置的kafka.fetch.from.beginning是true或者false，都会从topic的最开始拉取数据
 if (pendingOffsets.isEmpty() || pendingOffsets.size() <= 0) {
         lastOffset = emittingOffset;
 } else {
         lastOffset = pendingOffsets.first();
}
是不是应该改成啊，我改成如下的，就能从上次提交的offset读取数据了，而不是每次都从beginning拉取
 if (！pendingOffsets.isEmpty() || pendingOffsets.size() >= 0) {
        ..............
}

**Comment by JellyJellyJay** [comment]
源代码里面是获取的pendingOffsets.first，这个地方是不是有问题，我改成last之后消费kafka就没有问题了
 if (pendingOffsets.isEmpty() || pendingOffsets.size() <= 0) {
         lastOffset = emittingOffset;
 } else {
          //zr
          lastOffset = pendingOffsets.last();
  }

**Comment by jiankunking** [comment]
PartitionConsumer 中的代码是jstorm官方提供的，具体可以参加：
[https://github.com/alibaba/jstorm/blob/master/jstorm-utility/jstorm-kafka/src/main/java/com/alibaba/jstorm/kafka/PartitionConsumer.java](url)
